### ISSUE TITLE
选项卡中加入较长的列表时不能完全显示

### ISSUE THREAD

**Issue by Tingday** [15157757001/tabs#1]
`<cl-tabs :tab-bars="tabBars" :tab-index="tabCurrentIndex" @tabChange="tabChange" :scale="1.3" ref="tabs0"></cl-tabs>
<swiper class="swiper" :duration="300" @transition="transition" @change="changeCurrent" :current="tabCurrentIndex" @animationfinish="animationfinish">
<swiper-item v-for="(item,index) in tabBars" :key="index">
<view v-for="(item, index) in goodsList" :key="index" url="../detail/detail" @tap="setCouponInfo" :data-index="index">
{{goods}}
</view>
</swiper-item>
</swiper>
`
**当goodslist足够大时，会超出.swiper.height
请问如何做才能完全显示呢？**

**Comment by 15157757001** [comment]
```
<swiper-item v-for="(item,index) in tabBars" :key="index">
				<scroll-view scroll-y>
					<view v-for="(item, index) in goodsList" :key="index" url="../detail/detail" @tap="setCouponInfo" :data-index="index"> {{goods}} </view>
				
				</scroll-view>
			</swiper-item>
```

**Comment by 15157757001** [comment]
配个scroll-view

**Comment by Tingday** [comment]
谢谢！
